# Generated by Django 3.1.4 on 2021-01-04 14:26

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrigamiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=1000000000)),
                ('user', models.ForeignKey(on_delete=builtins.any, to='OrigamiApp.userprofile')),
            ],
        ),
    ]
