# Generated by Django 3.1.4 on 2021-01-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrigamiApp', '0002_userblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blog_covers'),
        ),
        migrations.AddField(
            model_name='userblog',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
