# Generated by Django 3.1.4 on 2021-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrigamiApp', '0005_auto_20210105_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blog_covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
