# Generated by Django 3.1.4 on 2021-01-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrigamiApp', '0006_auto_20210105_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='cover',
            field=models.FileField(blank=True, upload_to='blog_covers/'),
        ),
    ]
