# Generated by Django 3.1.4 on 2021-01-06 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrigamiApp', '0007_auto_20210105_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='blog',
            field=models.TextField(max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
